# Core packages
cask "rectangle-pro"
cask "hammerspoon"
brew "tmux"
brew "mise"
brew "opencode"
brew "lazygit"
brew "lazydocker"
brew "starship"
brew "zoxide"
brew "eza"
brew "jq"
brew "gum"
brew "gh"
brew "git"
brew "tailscale"
cask "font-jetbrains-mono-nerd-font"

# GUI Applications
cask "1password"
cask "docker-desktop"
cask "google-chrome"
cask "dropbox"
cask "spotify"
cask "signal"
cask "whatsapp"
cask "obsidian"
cask "claude-code"
cask "raycast"
cask "zoom"
